### ISSUE TITLE
custom.py error

### ISSUE THREAD

**Issue by thtl1999** [18-2-SKKU-OSS/2018-2-OSS-L4#1]
Traceback (most recent call last):
  File "C:/Users/thtl2/Downloads/bottest/MusicBot/custom.py", line 12, in <module>
    f1.write(f2.read())
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 79731: illegal multibyte sequence

Process finished with exit code 1

**Comment by ChoKyuWon** [comment]
유니코드 읽는 데서 문제가 난 것 같은데 custom.py에서 한글 입력 받는 부분 수정이 필요한 것 같네요
