### ISSUE TITLE
이게 command file을 이렇게 고치는 게 아닌가요?

### ISSUE THREAD

**Issue by minkyu1180** [18-2-SKKU-OSS/2018-2-OSS-L4#10]
![image](https://user-images.githubusercontent.com/36839753/49775410-815c2e80-fd3b-11e8-9e22-2b7e5d7b95c6.png)

고치고
update.py를 실행시키고
run.py를 실행시키면 되어야 하는 것 아닌가요?
!종료를 쳤는데 안되어서요..

**Comment by minkyu1180** [comment]
일단 win.bat에서 한번에 update와 실행까지 다 되도록 바꿔놓긴 했는데 그게 잘 안되어서 따로따로 해보니
안되더라고요.

**Comment by minkyu1180** [comment]
https://stackoverflow.com/questions/12122535/keep-multiple-console-windows-open-from-batch
아! 동시실행은 이거보고 참고했습니다

**Comment by thtl1999** [comment]
command를 바꾸는 방법은 맞습니다. 먼저 bot.py가 modify 되었는지 확인해보세요. 만약 bot.py가 modifiy 되었는데도 !종료 커맨드가 작동하지 않으면 modify 되기전에 실행되서 그런걸지도 모르겠네요. 또한 shutdown 커맨드는 owner만 사용 가능할것같으니 권한도 확인해보시면 좋을거같네요

**Comment by minkyu1180** [comment]
해결하였습니다. 실수로 update.py를 실행해놓게 하였네요..
custom.py가 아니라요
