### ISSUE TITLE
한글화 이슈

### ISSUE THREAD

**Issue by ChoKyuWon** [18-2-SKKU-OSS/2018-2-OSS-L4#2]
custom 커맨드 목록을 좀 봤는데 한글화하거나 다른걸로 바꾸기 좀 그런 커맨드들이 몇개 보이네요
`cmd_joinserver` 나  `cmd_balcklist` 같은 것들은 바꾸기 힘들뿐더러 굳이 바꿔야되나 하는 생각이 드는데 좋은 의견 있으신분 있나요?

**Comment by thtl1999** [comment]
유저에게 필요한 특정 커맨드만 바꿀 수 있게 하면 어떨까요?

**Comment by ChoKyuWon** [comment]
그러면 정말 좋겠지만 유저가 정확히 어떤 커맨드를 필요로 하는지 모른다는게 문제같습니다.
유저가 자기가 필요한 커맨드만 바꿀 수 있게 허용해도 되겠지만 소스 코드를 유저가 수정할 수 있게 되면 보안상 이슈가 생길 수도 있을 것 같고요

**Comment by ddyh2901** [comment]
사람들이 자주 사용하는 명령어 위주로 몇개만 바꿀수 있게 하는 게 좋지 않을까요?

**Comment by minkyu1180** [comment]
범용적인 이름으로 바꾼다면 큰 문제는 없어보일 것 같습니다.
사용자가 봇을 제작하고 배포하는 것이 아닌지라
