### ISSUE TITLE
위키 편집 이슈입니다

### ISSUE THREAD

**Issue by ChoKyuWon** [18-2-SKKU-OSS/2018-2-OSS-L4#4]
팀 멤버 페이지 새로 만들었습니다.

# 이름
## 소개

식으로 작성했습니다. 추후 수정이 필요해 보입니다.

**Comment by ChoKyuWon** [comment]
### 이름
#### 역할
#### 깃허브 ID
#### 메일
#### 학번 
***
포멧으로 업데이트했습니다

**Comment by ChoKyuWon** [comment]
메인 페이지에 team member profile로 가는 링크를 추가했습니다

**Comment by ChoKyuWon** [comment]
README.md 초반부분 번역해서 위키에 추가 완료

**Comment by ddyh2901** [comment]
Team project blog 페이지 새로 추가했습니다.

추후 수정이 필요해 보입니다.

**Comment by ChoKyuWon** [comment]
README.md 번역 완료, Team project blog 페이지 메인 페이지와 링크 완료

**Comment by ChoKyuWon** [comment]
Custom command(우리가 만드는 기능)을 설명해줄 위키 페이지를 만들었습니다.

**Comment by ChoKyuWon** [comment]
Command 설명 페이지 추가, 레이아웃 편집, 일부 번역 완료

**Comment by ChoKyuWon** [comment]
command 번역 3/4 완료

**Comment by ChoKyuWon** [comment]
https://github.com/18-2-SKKU-OSS/2018-2-OSS-L4/wiki/Custom-Command 커스텀 커맨드 역할 및 동작 원리 서술

**Comment by ChoKyuWon** [comment]
커맨드 번역 완료

**Comment by minkyu1180** [comment]
wiki에 있던 readme.md를 실제 README.md에 적용했습니다

**Comment by ChoKyuWon** [comment]
필요한 위키 편집은 다 한것같아 이슈 닫습니다
