### ISSUE TITLE
Custom.py 위치 조정

### ISSUE THREAD

**Issue by ChoKyuWon** [18-2-SKKU-OSS/2018-2-OSS-L4#9]
Custom.py 위치를 MusicBot 폴더 안에 넣고 run 스크립트를 수정해 자동으로 실행하게 하는게 어떤가요?

**Comment by ChoKyuWon** [comment]
run.bat이 custom.py까지 실행할 수 있게 수정중인데 잘 안됩니다...

**Comment by minkyu1180** [comment]
run.sh가 custom.py까지 실행할 수 있게 수정중입니다

**Comment by thtl1999** [comment]
custom.py의 위치를 /musicbot 으로 옮기고 github에 push 했습니다

**Comment by ChoKyuWon** [comment]
custom.bat 수정 완료했습니다
